// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectHub.Data.Contexts;

#nullable disable

namespace ProjectHub.Data.Migrations
{
    [DbContext(typeof(ProjectHubSqLiteDbContext))]
    [Migration("20231220170638_SeedTestDataForFilteringSorting")]
    partial class SeedTestDataForFilteringSorting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("ProjectHub.Data.Abstractions.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Assembly"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Befunge"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brainfuck"
                        },
                        new
                        {
                            Id = 4,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chef"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Clojure"
                        },
                        new
                        {
                            Id = 8,
                            Name = "COBOL"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dart"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Elm"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Elixir"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Erlang"
                        },
                        new
                        {
                            Id = 13,
                            Name = "F#"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Fortran"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Go"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Groovy"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Haskell"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 19,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Lisp"
                        },
                        new
                        {
                            Id = 22,
                            Name = "LOLCODE"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Lua"
                        },
                        new
                        {
                            Id = 24,
                            Name = "MATLAB"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Objective-C"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Pascal"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Perl"
                        },
                        new
                        {
                            Id = 28,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Piet"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Prolog"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 32,
                            Name = "R"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Rust"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Scala"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Shakespeare"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Swift"
                        },
                        new
                        {
                            Id = 38,
                            Name = "TrumpScript"
                        },
                        new
                        {
                            Id = 39,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Whitespace"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Webassembly"
                        },
                        new
                        {
                            Id = 42,
                            Name = "keine Vorgabe"
                        });
                });

            modelBuilder.Entity("ProjectHub.Data.Abstractions.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TribeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserUuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TribeId");

                    b.HasIndex("UserUuid");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2002, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 1",
                            Status = "New",
                            Title = "Project Title 1",
                            TribeId = 2,
                            UserUuid = "AlexW@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2017, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 2",
                            Status = "New",
                            Title = "Project Title 2",
                            TribeId = 3,
                            UserUuid = "DiegoS@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2003, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 3",
                            Status = "New",
                            Title = "Project Title 3",
                            TribeId = 4,
                            UserUuid = "GradyA@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2018, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 4",
                            Status = "New",
                            Title = "Project Title 4",
                            TribeId = 5,
                            UserUuid = "HenriettaM@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2004, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 5",
                            Status = "New",
                            Title = "Project Title 5",
                            TribeId = 6,
                            UserUuid = "IsaiahL@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2019, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 6",
                            Status = "New",
                            Title = "Project Title 6",
                            TribeId = 7,
                            UserUuid = "JohannaL@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2006, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 7",
                            Status = "New",
                            Title = "Project Title 7",
                            TribeId = 8,
                            UserUuid = "JoniS@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2021, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 8",
                            Status = "New",
                            Title = "Project Title 8",
                            TribeId = 9,
                            UserUuid = "LeeG@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2007, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 9",
                            Status = "New",
                            Title = "Project Title 9",
                            TribeId = 10,
                            UserUuid = "LidiaH@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2022, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 10",
                            Status = "New",
                            Title = "Project Title 10",
                            TribeId = 11,
                            UserUuid = "LynneR@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2008, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 11",
                            Status = "New",
                            Title = "Project Title 11",
                            TribeId = 12,
                            UserUuid = "AdeleV@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 12",
                            Status = "New",
                            Title = "Project Title 12",
                            TribeId = 1,
                            UserUuid = "AlexW@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2009, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 13",
                            Status = "New",
                            Title = "Project Title 13",
                            TribeId = 2,
                            UserUuid = "DiegoS@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(1996, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 14",
                            Status = "New",
                            Title = "Project Title 14",
                            TribeId = 3,
                            UserUuid = "GradyA@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2011, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 15",
                            Status = "New",
                            Title = "Project Title 15",
                            TribeId = 4,
                            UserUuid = "HenriettaM@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(1997, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 16",
                            Status = "New",
                            Title = "Project Title 16",
                            TribeId = 5,
                            UserUuid = "IsaiahL@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2012, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 17",
                            Status = "New",
                            Title = "Project Title 17",
                            TribeId = 6,
                            UserUuid = "JohannaL@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(1998, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 18",
                            Status = "New",
                            Title = "Project Title 18",
                            TribeId = 7,
                            UserUuid = "JoniS@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2013, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 19",
                            Status = "New",
                            Title = "Project Title 19",
                            TribeId = 8,
                            UserUuid = "LeeG@ynl4z.onmicrosoft.com"
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2000, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Project Description 20",
                            Status = "New",
                            Title = "Project Title 20",
                            TribeId = 9,
                            UserUuid = "LidiaH@ynl4z.onmicrosoft.com"
                        });
                });

            modelBuilder.Entity("ProjectHub.Data.Abstractions.Entities.ProjectProgrammingLanguages", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgrammingLanguageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "ProgrammingLanguageId");

                    b.HasIndex("ProgrammingLanguageId");

                    b.ToTable("ProjectProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            ProgrammingLanguageId = 1
                        },
                        new
                        {
                            ProjectId = 2,
                            ProgrammingLanguageId = 2
                        },
                        new
                        {
                            ProjectId = 3,
                            ProgrammingLanguageId = 3
                        },
                        new
                        {
                            ProjectId = 4,
                            ProgrammingLanguageId = 4
                        },
                        new
                        {
                            ProjectId = 5,
                            ProgrammingLanguageId = 5
                        },
                        new
                        {
                            ProjectId = 6,
                            ProgrammingLanguageId = 6
                        },
                        new
                        {
                            ProjectId = 7,
                            ProgrammingLanguageId = 7
                        },
                        new
                        {
                            ProjectId = 8,
                            ProgrammingLanguageId = 8
                        },
                        new
                        {
                            ProjectId = 9,
                            ProgrammingLanguageId = 9
                        },
                        new
                        {
                            ProjectId = 10,
                            ProgrammingLanguageId = 10
                        },
                        new
                        {
                            ProjectId = 11,
                            ProgrammingLanguageId = 11
                        },
                        new
                        {
                            ProjectId = 12,
                            ProgrammingLanguageId = 12
                        },
                        new
                        {
                            ProjectId = 13,
                            ProgrammingLanguageId = 13
                        },
                        new
                        {
                            ProjectId = 14,
                            ProgrammingLanguageId = 14
                        },
                        new
                        {
                            ProjectId = 15,
                            ProgrammingLanguageId = 15
                        },
                        new
                        {
                            ProjectId = 16,
                            ProgrammingLanguageId = 16
                        },
                        new
                        {
                            ProjectId = 17,
                            ProgrammingLanguageId = 17
                        },
                        new
                        {
                            ProjectId = 18,
                            ProgrammingLanguageId = 18
                        },
                        new
                        {
                            ProjectId = 19,
                            ProgrammingLanguageId = 19
                        },
                        new
                        {
                            ProjectId = 20,
                            ProgrammingLanguageId = 20
                        },
                        new
                        {
                            ProjectId = 1,
                            ProgrammingLanguageId = 21
                        },
                        new
                        {
                            ProjectId = 2,
                            ProgrammingLanguageId = 22
                        },
                        new
                        {
                            ProjectId = 3,
                            ProgrammingLanguageId = 23
                        },
                        new
                        {
                            ProjectId = 4,
                            ProgrammingLanguageId = 24
                        },
                        new
                        {
                            ProjectId = 5,
                            ProgrammingLanguageId = 25
                        },
                        new
                        {
                            ProjectId = 6,
                            ProgrammingLanguageId = 26
                        },
                        new
                        {
                            ProjectId = 7,
                            ProgrammingLanguageId = 27
                        },
                        new
                        {
                            ProjectId = 8,
                            ProgrammingLanguageId = 28
                        },
                        new
                        {
                            ProjectId = 9,
                            ProgrammingLanguageId = 29
                        },
                        new
                        {
                            ProjectId = 10,
                            ProgrammingLanguageId = 30
                        });
                });

            modelBuilder.Entity("ProjectHub.Data.Abstractions.Entities.Tribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tribes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tribe Alpha"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tribe Chi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tribe Delta"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tribe Gamma"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tribe Iota"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tribe Lambda"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tribe My"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tribe Omega"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tribe Psi"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tribe Sigma"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Tribe Tau"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tribe Xi"
                        });
                });

            modelBuilder.Entity("ProjectHub.Data.Abstractions.Entities.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Email = "AdeleV@ynl4z.onmicrosoft.com",
                            FirstName = "Adele",
                            LastName = "Vance"
                        },
                        new
                        {
                            Email = "AlexW@ynl4z.onmicrosoft.com",
                            FirstName = "Alex",
                            LastName = "Wilber"
                        },
                        new
                        {
                            Email = "DiegoS@ynl4z.onmicrosoft.com",
                            FirstName = "Diego",
                            LastName = "Siciliani"
                        },
                        new
                        {
                            Email = "GradyA@ynl4z.onmicrosoft.com",
                            FirstName = "Grady",
                            LastName = "Archie"
                        },
                        new
                        {
                            Email = "HenriettaM@ynl4z.onmicrosoft.com",
                            FirstName = "Henrietta",
                            LastName = "Mueller"
                        },
                        new
                        {
                            Email = "IsaiahL@ynl4z.onmicrosoft.com",
                            FirstName = "Isaiah",
                            LastName = "Langer"
                        },
                        new
                        {
                            Email = "JohannaL@ynl4z.onmicrosoft.com",
                            FirstName = "Johanna",
                            LastName = "Lorenz"
                        },
                        new
                        {
                            Email = "JoniS@ynl4z.onmicrosoft.com",
                            FirstName = "Joni",
                            LastName = "Sherman"
                        },
                        new
                        {
                            Email = "LeeG@ynl4z.onmicrosoft.com",
                            FirstName = "Lee",
                            LastName = "Gu"
                        },
                        new
                        {
                            Email = "LidiaH@ynl4z.onmicrosoft.com",
                            FirstName = "Lidia",
                            LastName = "Holloway"
                        },
                        new
                        {
                            Email = "LynneR@ynl4z.onmicrosoft.com",
                            FirstName = "Lynne",
                            LastName = "Robbins"
                        });
                });

            modelBuilder.Entity("ProjectHub.Data.Abstractions.Entities.Project", b =>
                {
                    b.HasOne("ProjectHub.Data.Abstractions.Entities.Tribe", "Tribe")
                        .WithMany()
                        .HasForeignKey("TribeId");

                    b.HasOne("ProjectHub.Data.Abstractions.Entities.User", "User")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("UserUuid");

                    b.Navigation("Tribe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectHub.Data.Abstractions.Entities.ProjectProgrammingLanguages", b =>
                {
                    b.HasOne("ProjectHub.Data.Abstractions.Entities.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany("ProjectProgrammingLanguages")
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectHub.Data.Abstractions.Entities.Project", "Project")
                        .WithMany("projectProgrammingLanguages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammingLanguage");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectHub.Data.Abstractions.Entities.ProgrammingLanguage", b =>
                {
                    b.Navigation("ProjectProgrammingLanguages");
                });

            modelBuilder.Entity("ProjectHub.Data.Abstractions.Entities.Project", b =>
                {
                    b.Navigation("projectProgrammingLanguages");
                });

            modelBuilder.Entity("ProjectHub.Data.Abstractions.Entities.User", b =>
                {
                    b.Navigation("CreatedProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
